services:
  db:
    image: 'postgres:16.1-alpine'
    container_name: db
    environment:
      POSTGRES_DB: "shareIt_database"
      POSTGRES_USER: "elPrimo"
      POSTGRES_PASSWORD: "password"
      POSTGRES_ROOT_PASSWORD: "password"
    ports:
      - "5432:5432"
